# Generated by Django 6.0.1 on 2026-01-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_farmerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
