# Generated by Django 5.2.10 on 2026-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0005_croprecommendation_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croprecommendation',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='croprecommendation',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='croprecommendation',
            name='potassium',
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='climate',
            field=models.CharField(default='moderate', max_length=100),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='fertility',
            field=models.CharField(default='medium', max_length=100),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='rainfall_level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='recommended_crops',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='soil_type',
            field=models.CharField(default='loamy', max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='humidity',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='ph',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='rainfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='recommended_crop',
            field=models.CharField(default='Rice', max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='temperature',
            field=models.FloatField(default=25),
        ),
    ]
