# Generated by Django 5.2.10 on 2026-02-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0006_remove_croprecommendation_nitrogen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croprecommendation',
            name='confidence',
        ),
    ]
