# Generated by Django 5.2.10 on 2026-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0004_croprecommendation_diseasedetection_marketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='nitrogen',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='phosphorus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='rainfall',
            field=models.FloatField(default=0),
        ),
    ]
